name: "ds_for_fastpitch_align"

manifest_filepath: "train_manifest.json"
sup_data_path: "sup_data"
sup_data_types: [ "align_prior_matrix", "pitch", "energy" ]

dataloader_params:
  num_workers: 16
dataset:
  _target_: roar.collections.tts.data.dataset.TTSDataset
  manifest_filepath: ${manifest_filepath}
  sample_rate: 22050
  sup_data_path: ${sup_data_path}
  sup_data_types: ${sup_data_types}
  n_fft: 1024
  win_length: 1024
  hop_length: 256
  window: "hann"
  n_mels: 80
  lowfreq: 0
  highfreq: 8000
  max_duration: null
  min_duration: 0.1
  ignore_file: null
  trim: false
  pitch_fmin: 65.40639132514966
  pitch_fmax: 2093.004522404789

  text_tokenizer:
    _target_: roar.collections.common.tokenizers.text_to_speech.tts_tokenizers.TamilCharsTokenizer
    punct: true
    apostrophe: true
    pad_with_space: true